# 1 lấy image có sẵn của Spark version 3.4.1 từ Docker Hub
FROM apache/spark:3.4.1

# 2 chuyển sang user root ( chạy container với quyền admin)
USER root

# 3 copy các file thư viện .jar
COPY jars/*.jar /opt/spark/jars/

# 4 copy code batch
COPY jobs/ /opt/spark/batch/jobs

# 5. Set PYTHONPATH để fix lỗi import
ENV PYTHONPATH=/opt/spark/batch/jobs

# 6. Set working directory
WORKDIR /opt/spark/batch