apiVersion: apps/v1
kind: Deployment #StatefulSet = giữ dữ liệu khi pod chết
metadata:
  name: minio             # tên deployment     
spec:
  replicas: 1             
  selector:               # khai báo cho bộ lọc tìm kiếm
    matchLabels:
      app: minio
  template:               # template->metadata->labels = nhãn thật sự (Label) được dán lên con Pod khi nó được sinh ra
    metadata:
      labels:
        app: minio        # nhãn của pod này
    spec:                 # trong pod này có cái container bên dưới
      containers:         # nghĩa là trong 1 pod có thể nhiều container, do đó vẫn phải đặt tên định danh riêng
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"] # mày là server, có /data là nơi cất trữ liệu trong container của mày, mở thêm giao diện, ở port 9001
          env:                      # các biến môi trường, UI hay backend khác muốn truy cập đều cần
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:                    # khai báo nội bộ trong container này
            - containerPort: 9000   # cổng backend mặc định của MinIO 
            - containerPort: 9001   # mở UI console
          resources:                # lượng tài nguyên mà pod yêu cầu thì nó mới chịu chạy
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          
---
apiVersion: v1
kind: Service             # Service = đường mạng
metadata:
  name: minio-service             # tên service
spec:
  type: NodePort
  selector:
    app: minio            # service sẽ chọn các pod có tên label
  ports:                  # cổng Service quản lý
    - name: api           # là tên định danh cổng backend (tự đặt)
      port: 9000          # port trong service
      targetPort: 9000    # chuyển request vào container port 9000
    - name: console       # tên cổng khác là cổng UI
      port: 9001          # tương tự
      targetPort: 9001
      nodePort: 30091
---