apiVersion: v1
kind: Service             # tạo 1 Service tên spark-master
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:                     # cấu hình
  type: ClusterIP         # chỉ truy cập được trong cluster (ko public ra internet)
  ports:
    - port: 7077          # port chính của Spark Master
      name: rpc
      targetPort: 7077
    - port: 8080          # port của UI
      name: web-ui
      targetPort: 8080
  selector:               # Service sẽ “bám vào” các Pod có label: spark-master
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment          # chạy Spark Master
metadata:                 
  name: spark-master      
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:               # chỉ 1 Spark master
    matchLabels:
      app: spark-master
  template:               # Pod template
    metadata:
      labels:
        app: spark-master
    spec:
      enableServiceLinks: false  # Tắt tính năng tự động inject các biến môi trường từ Service vào container.
      containers:
        - name: spark-master
          image: apache/spark:3.4.1
          command:
            [
              "/opt/spark/bin/spark-class", # launcher của Spark
              "org.apache.spark.deploy.master.Master" # chạy chế độ Spark Master thật, các name ở trên chỉ là tự đặt
            ]
          ports:                    # khai báo 2 port
            - containerPort: 7077
            - containerPort: 8080
          env:                      # bắt Spark chạy foreground (ko chạy nền)
            - name: SPARK_NO_DAEMONIZE
              value: "true"
          resources:
            requests:
              cpu: "500m"     # 0.5CPU
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment            # chạy Spark Master
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:                       # cấu hình
  replicas: 2               # chạy 2 worker node
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:                   # cấu hình pod
      containers:
        - name: spark-worker
          image: apache/spark:3.4.1
          command:
            [
              "/opt/spark/bin/spark-class",            # launcher của Spark
              "org.apache.spark.deploy.worker.Worker", # chạy chế độ Spark Worker
              "spark://spark-master:7077"              # kết nối đến Master qua spark://spark-master:7077
            ]
          env:
            - name: SPARK_WORKER_MEMORY
              value: "1g"
            - name: SPARK_WORKER_CORES
              value: "1"                  # 1 CPU
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"