apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" # Thư mục này nằm trên Node của Kind
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi