apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service             # tạo 1 Service tên spark-master
metadata:
  name: spark-master      # name của service
  labels:
    app: spark-master     # Gắn label để dễ quản lý.
spec:                     # cấu hình
  type: NodePort          # để truy cập UI từ máy host (Kind)
  ports:
    - name: rpc          
      port: 7077          # port chính của Spark Master
      targetPort: 7077
    - name: web-ui
      port: 8080          # port của UI
      targetPort: 8080
      nodePort: 30080     # UI: http://localhost:30080
  selector:               # Service sẽ “bám vào” các Pod có label: spark-master
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment          # chạy Spark Master
metadata:                 
  name: spark-master   
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:               # chỉ 1 Spark master
    matchLabels:
      app: spark-master
  template:               # Pod template
    metadata:
      labels:
        app: spark-master
    spec:
      enableServiceLinks: false  # Tắt tính năng tự động inject các biến môi trường từ Service vào container.
      containers:
        - name: spark-master
          image: apache/spark:3.4.1     #   minhquan-spark-image:latest # dùng image custom
          command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
          ports:                    # khai báo 2 port
            - containerPort: 7077
            - containerPort: 8080
          env:                      # bắt Spark chạy foreground (ko chạy nền)
            - name: SPARK_NO_DAEMONIZE
              value: "true"

            - name: SPARK_MASTER_HOST
              value: "spark-master"

          volumeMounts:
             - name: data
               mountPath: /opt/spark/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: csv-data-pvc
---
apiVersion: apps/v1
kind: Deployment            # chạy Worker
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:                       # cấu hình
  replicas: 2               # chạy 2 worker node
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:                   # cấu hình pod
      initContainers:
      - name: wait-master
        image: busybox
        command:
          - sh
          - -c
          - "until nc -z spark-master 7077; do echo waiting; sleep 2; done"
      containers:
        - name: spark-worker
          image: apache/spark:3.4.1
          imagePullPolicy: IfNotPresent
          command:
            [
              "/opt/spark/bin/spark-class",            # launcher của Spark
              "org.apache.spark.deploy.worker.Worker", # chạy chế độ Spark Worker
              "spark://spark-master:7077"              # kết nối đến Master qua spark://spark-master:7077
            ]
          env:
            - name: SPARK_WORKER_MEMORY
              value: "2g"
            - name: SPARK_WORKER_CORES
              value: "2"                  # 1 CPU
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
